### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by Son0208** [alanhyue/jupyter-darkmode#1]
Thanks for deploying the nice extension! 

It's nice that no additional plot settings are required!!

Suggestions : 

It would be nice if the 'Jupyter'(next to the title), 'Trust' , and 'Kernel Name' texts could be seen more clearly.

and also the 'ExecuteTime'(nbextension) text ^^;;

**Comment by alanhyue** [comment]
Hi @Son0208 , thanks for choosing darkmode and in addition, for proposing the first suggestion! Please update the plugin and you should be able to get the latest visual adjustments.

<img width="690" alt="image" src="https://github.com/alanhyue/jupyter-darkmode/assets/23422714/abb8b939-510b-43db-aa1a-d62ad4364e83">

**Comment by Son0208** [comment]
Thanks for fast reply!!
